#
# collection device and location
device: rpi3a-uat-vallejo1
#
# dump978 output file
dump978out: /tmp/aircraft.json
#
# collected files go here
exportDir: /Users/gsc/Documents/github/mellow-hyena/aws_export
#exportDir: /home/gsc/github/mellow-hyena/aws_export
#
rapidApiKey: bogus
#
