--
-- Title: adsb_ranking.psql
-- Description: which beacons are most common? 
--
create table adsb_ranking (
  id          bigserial    primary key,
  adsb_hex    varchar(12)  not null,
  population  int          not null,
  score_date  date         not null
);

grant select, insert, update, delete on adsb_ranking to hyena_py;
grant usage, select on sequence adsb_ranking_id_seq to hyena_py;

create unique index adsb_rank_date on adsb_ranking(score_date, adsb_hex);
